# DO NOT EDIT THIS FILE - it is automatically generated, edit file SettingsTemplate.mk

# Available libraries: mad (GPL-ed!) sdl_mixer sdl_image sdl_ttf sdl_net sdl_blitpool sdl_gfx sdl_sound intl xml2 lua jpeg png ogg flac tremor vorbis freetype xerces curl theora fluidsynth lzma lzo2 mikmod openal timidity zzip bzip2 yaml-cpp python boost_date_time boost_filesystem boost_iostreams boost_program_options boost_regex boost_signals boost_system boost_thread glu avcodec avdevice avfilter avformat avresample avutil swscale swresample bzip2 
APP_MODULES := application sdl-1.2 sdl_main sdl_native_helpers jpeg png ogg flac vorbis freetype jpeg png sdl_image sdl_gfx sdl_ttf guichan

# To filter out static libs from all libs in makefile
APP_AVAILABLE_STATIC_LIBS := jpeg png tremor freetype xerces ogg tremor vorbis flac boost_date_time boost_filesystem boost_iostreams boost_program_options boost_regex boost_signals boost_system boost_thread boost_locale glu icudata icutest icui18n icuio icule iculx icutu icuuc

APP_ABI := armeabi-v7a x86

# The namespace in Java file, with dots replaced with underscores
SDL_JAVA_PACKAGE_PATH := pandora_uae4all_sdl

# Path to files with application data - they should be downloaded from Internet on first app run inside
# Java sources, or unpacked from resources (TODO)
# Typically /sdcard/alienblaster 
# Or /data/data/de.schwardtnet.alienblaster/files if you're planning to unpack data in application private folder
# Your application will just set current directory there
SDL_CURDIR_PATH := pandora.uae4all.sdl

# Android Dev Phone G1 has trackball instead of cursor keys, and 
# sends trackball movement events as rapid KeyDown/KeyUp events,
# this will make Up/Down/Left/Right key up events with X frames delay,
# so if application expects you to press and hold button it will process the event correctly.
# TODO: create a libsdl config file for that option and for key mapping/on-screen keyboard
SDL_TRACKBALL_KEYUP_DELAY := 1

# If the application designed for higher screen resolution enable this to get the screen
# resized in HW-accelerated way, however it eats a tiny bit of CPU
SDL_VIDEO_RENDER_RESIZE := 1

COMPILED_LIBRARIES := jpeg png sdl_image sdl_gfx sdl_ttf guichan

APPLICATION_ADDITIONAL_CFLAGS := 

APPLICATION_ADDITIONAL_LDFLAGS := 

APPLICATION_OVERLAPS_SYSTEM_HEADERS := 

APPLICATION_SUBDIRS_BUILD := 

APPLICATION_BUILD_EXCLUDE := 

APPLICATION_CUSTOM_BUILD_SCRIPT := y

SDL_ADDITIONAL_CFLAGS := 		 -DSDL_ANDROID_KEYCODE_0=NO_REMAP -DSDL_ANDROID_KEYCODE_1=RETURN -DSDL_ANDROID_KEYCODE_2=NO_REMAP -DSDL_ANDROID_KEYCODE_3=NO_REMAP -DSDL_ANDROID_KEYCODE_4=LCTRL -DSDL_ANDROID_KEYCODE_5=LCTRL -DSDL_ANDROID_KEYCODE_6=NO_REMAP -DSDL_ANDROID_KEYCODE_7=RETURN -DSDL_ANDROID_KEYCODE_8=NO_REMAP -DSDL_ANDROID_KEYCODE_9=NO_REMAP 		 -DSDL_ANDROID_SCREENKB_KEYCODE_0=HOME -DSDL_ANDROID_SCREENKB_KEYCODE_1=END -DSDL_ANDROID_SCREENKB_KEYCODE_2=PAGEDOWN -DSDL_ANDROID_SCREENKB_KEYCODE_3=PAGEUP -DSDL_ANDROID_SCREENKB_KEYCODE_4=RCTRL -DSDL_ANDROID_SCREENKB_KEYCODE_5=RSHIFT -DSDL_ANDROID_SCREENKB_KEYCODE_6=UNKNOWN -DSDL_ANDROID_SCREENKB_KEYCODE_7=UNKNOWN -DSDL_ANDROID_SCREENKB_KEYCODE_8=UNKNOWN 		 -DSDL_ANDROID_GAMEPAD_KEYCODE_0=HOME -DSDL_ANDROID_GAMEPAD_KEYCODE_1=END -DSDL_ANDROID_GAMEPAD_KEYCODE_2=PAGEDOWN -DSDL_ANDROID_GAMEPAD_KEYCODE_3=PAGEUP -DSDL_ANDROID_GAMEPAD_KEYCODE_4=RCTRL -DSDL_ANDROID_GAMEPAD_KEYCODE_5=RSHIFT -DSDL_ANDROID_GAMEPAD_KEYCODE_6=F14 -DSDL_ANDROID_GAMEPAD_KEYCODE_7=F15 -DSDL_ANDROID_GAMEPAD_KEYCODE_8=PAGEDOWN -DSDL_ANDROID_GAMEPAD_KEYCODE_9=HOME -DSDL_ANDROID_GAMEPAD_KEYCODE_10=LCTRL 		 		-DSDL_AUDIO_APP_IGNORES_RETURNED_BUFFER_SIZE=1 		-DSDL_COMPATIBILITY_HACKS_SLOW_COMPATIBLE_EVENT_QUEUE=1 		 		

SDL_VERSION := 1.2

